/*
    This file was autogenerated by buttonparse
*/

#ifndef _SPP_DEV_B_BUTTONS_H
#define _SPP_DEV_B_BUTTONS_H

#include <message.h>

/* messages sent to the client */
enum
{
	POWER_BUTTON_PRESS = 1000 /* base value */,
	POWER_BUTTON_RELEASE,
	FUNCTION_BUTTON_PRESS,
	PIO_RAW
};

typedef enum
{
	sPOWER_BUTTON,
	sSCAN_BUTTON,
	Unknown
} InternalState;

typedef struct
{
	uint16 pio;
} PIO_RAW_T;

typedef struct
{
	InternalState store_held;
	InternalState double_press;
	uint16 pio_raw_bits;
	uint16 pskey_wakeup;
	uint16 store_bits;
	uint16 store_count;
	uint16 timed_id;
} PioStoredState;

typedef struct
{
	TaskData task;
	Task client;
	PioStoredState pio_states;
} PioState;

void pioInit(PioState *state, Task client);

#endif
